### ISSUE TITLE
pyppeteer hangs when using it with nest_asyncio

### ISSUE THREAD

**Issue by Zincr0** [pyppeteer/pyppeteer#99]
nest_asyncio is currently the only way to run async code that has is own main loop on jupyter or ipython. 

pyppeteer (the original project) was until a few versions, compatible with nest_asyncio, but the last version is broken the same way as pyppeteer2. 

If you run this:

```
import asyncio
from pyppeteer import launch
import nest_asyncio

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://www.google.cl')
    await page.screenshot({'path': 'example.png'})
    await browser.close()


nest_asyncio.apply()
asyncio.get_event_loop().run_until_complete(main())
```
The code will hang forever at at `browser = await launch()`, with no error messages at all.

Note that this only happens with launch() from pyppeteer, every other async function will run just fine with nest_asyncio  (is not a nest_asyncio bug).

Tested on python 3.7.6

**Comment by Mattwmaster58** [comment]
> If you run this:
>
> 
```py
import asyncio
from pyppeteer import launch
import nest_asyncio

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://www.google.cl')
    await page.screenshot({'path': 'example.png'})
    await browser.close()


nest_asyncio.apply()
asyncio.get_event_loop().run_until_complete(main())
```

Is that within an ipython console session? 

Looking into the bug that nested_async mentions, someone mentioned this: 

> the very programming technique that you are proposing has caused some very hard to debug problems

Which seems exactly like what's happening here.

**Comment by Mattwmaster58** [comment]
Also, is there any reason why you don't just simply use a bare await in ipython/jupyter? It seems to support that just fine.

**Comment by Zincr0** [comment]
It is not running from an ipython session, this is for code for an external library that _may_ be called from an application that has is own main asyncio loop. 
Since there's no control outside of the library, nest_asyncio is needed to allow nested loops, to wrap the main function inside another non-async function (that has is own `run_until_complete` with a manually created loop), so the function library can be called from external async or non async code.

**Comment by Zincr0** [comment]
This also causes that using IPython `embed` inside the code fails with a "main loop already running error" (when not using nest_asyncio, nothing strange really since avoid that error is the main purpose of the library)

**Comment by SylvainCorlay** [comment]
Encountering the same issue with `nest_asyncio` making `launch` hang.

Does anyone know of a workaround?

**Comment by milahu** [comment]
edit: im stupid. i had the file `secrets.py` in my working directory
which shadowed python's `secrets` module and broke the `websockets` module

```
AttributeError: module 'secrets' has no attribute 'token_bytes'
```

fixed by renaming the file to `my_secrets.py`

now it works with both 4e88a900bff77b63e62b88bed5afd5f78902db27 and #16

<details>

> The code will hang forever at at `browser = await launch()`

same problem with `asyncio` and pyppeteer 1.0.2
same problem with `asyncio` and pyppeteer 4e88a900bff77b63e62b88bed5afd5f78902db27

`pyppeteer.launch` hangs forever

killing the script gives

```
RuntimeError: This event loop is already running
2023-10-22 09:43:07,910 INFO terminate chrome process...
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-10-22 09:43:08,012 ERROR Task was destroyed but it is pending!

AttributeError: module 'secrets' has no attribute 'token_bytes'
```

similar: #400 #308 #290 

<details>

```py
import os
import logging
import asyncio

pyppeteer_headless = False

def logger_print(*args):
    logging.info(" ".join(map(str, args)))

logging.basicConfig(
    format='%(asctime)s %(levelname)s %(message)s',
    level="DEBUG",
)

async def main():
    logger_print("import pyppeteer")
    import pyppeteer
    logger_print("pyppeteer.launch")

    # FIXME this hangs
    pyppeteer_browser = await pyppeteer.launch(
        # https://pptr.dev/api/puppeteer.puppeteerlaunchoptions
        headless=pyppeteer_headless,
        # path to /bin/chromium
        # chrome binaries from ~/.cache/puppeteer/chrome are not working on nixos linux
        # ldd ~/.cache/puppeteer/chrome/linux-*/chrome-linux/chrome | grep "not found"
        executablePath=os.environ["PUPPETEER_EXECUTABLE_PATH"],
        args=[
            # no effect
            #"--disable-blink-features=AutomationControlled",
        ],
    )

    logger_print("pyppeteer_browser.newPage")
    pyppeteer_page = await pyppeteer_browser.newPage()

    for url, path in [
        ('https://hmaker.github.io/selenium-detector/', 'chrome_headless_stealth.selenium-detector.png'),
        ('https://bot.sannysoft.com/', 'chrome_headless_stealth.bot.sannysoft.com.png'), # outdated
        ('https://abrahamjuliot.github.io/creepjs/', 'chrome_headless_stealth.creepjs.png'),
        ('http://f.vision/', 'chrome_headless_stealth.fake-vision.png'),
    ]:
        logger_print("pyppeteer_page.goto", url)
        await pyppeteer_page.goto(url)
        if url == 'https://abrahamjuliot.github.io/creepjs/':
            await asyncio.sleep(10)
        logger_print("pyppeteer_page.screenshot", path)
        await pyppeteer_page.screenshot(path=path, fullPage=True)

asyncio.get_event_loop().run_until_complete(main())
```

```
2023-10-22 09:41:23,686 DEBUG Using selector: EpollSelector
2023-10-22 09:41:23,687 INFO import pyppeteer
2023-10-22 09:41:24,358 INFO pyppeteer.launch
2023-10-22 09:41:26,935 INFO Browser listening on: ws://127.0.0.1:43999/devtools/browser/531b2dc5-ad2d-4076-bfbc-32cfd8b10257
2023-10-22 09:41:26,941 DEBUG SEND: {"id": 1, "method": "Target.setDiscoverTargets", "params": {"discover": true}}
2023-10-22 09:41:26,947 DEBUG = connection is CONNECTING
2023-10-22 09:41:26,950 DEBUG ! failing connection with code 1006
2023-10-22 09:41:26,952 DEBUG x half-closing TCP connection
2023-10-22 09:41:26,954 DEBUG = connection is CLOSED

^C2023-10-22 09:43:05,253 ERROR Exception in callback <TaskStepMethWrapper object at 0x7f1c67443fa0>()
handle: <Handle <TaskStepMethWrapper object at 0x7f1c67443fa0>()>
Traceback (most recent call last):
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 513, in _check_closed
    def _check_closed(self):
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 584, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

^CTraceback (most recent call last):
  File "/home/user/src/opensubtitles-scraper/test-pyppeteer.py", line 49, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 584, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2023-10-22 09:43:07,910 INFO terminate chrome process...
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-10-22 09:43:08,012 ERROR Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._async_send() running at /nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/pyppeteer/connection.py:71>>
2023-10-22 09:43:08,037 ERROR Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Connection._recv_loop() done, defined at /nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/pyppeteer/connection.py:53> exception=AttributeError("module 'secrets' has no attribute 'token_bytes'")>
Traceback (most recent call last):
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/pyppeteer/connection.py", line 54, in _recv_loop
    async with self._ws as connection:
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 303, in handshake
    key = build_request(request_headers)
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/handshake.py", line 30, in build_request
    key = generate_key()
  File "/nix/store/k4wmw3mcyx9z7jc63xyvraccg7jmxyav-python3-3.10.12-env/lib/python3.10/site-packages/websockets/utils.py", line 20, in generate_key
    key = secrets.token_bytes(16)
AttributeError: module 'secrets' has no attribute 'token_bytes'
```

</details>

also fails with #16

```
AttributeError: module 'secrets' has no attribute 'token_bytes'
```

<details>

```
2023-10-22 10:12:54,807 DEBUG Using selector: EpollSelector
2023-10-22 10:12:54,808 INFO import pyppeteer
2023-10-22 10:12:56,816 INFO pyppeteer.launch
2023-10-22 10:12:56,860 DEBUG Calling process: /nix/store/z37vp487cvp7ilnwmsi39f4m94ljwpsv-ungoogled-chromium-117.0.5938.149/bin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain about:blank --remote-debugging-port=38621 --user-data-dir=/run/user/1000/pyppeteer_chrome_profile_11wsh_n4
2023-10-22 10:12:58,714 DEBUG = connection is CONNECTING
2023-10-22 10:12:58,716 DEBUG ! failing connection with code 1006
2023-10-22 10:12:58,717 DEBUG x half-closing TCP connection
2023-10-22 10:12:58,723 DEBUG = connection is CLOSED
2023-10-22 10:12:58,725 ERROR error occurred while trying to launch browser: module 'secrets' has no attribute 'token_bytes'
Traceback (most recent call last):
  File "/home/user/src/opensubtitles-scraper/test-pyppeteer.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/src/opensubtitles-scraper/test-pyppeteer.py", line 22, in main
    pyppeteer_browser = await pyppeteer.launch(
  File "/home/user/src/opensubtitles-scraper/pyppeteer/pyppeteer/__init__.py", line 100, in launch
    return await Pyppeteer(projectRoot, preferredRevision).launch(**kwargs)
  File "/home/user/src/opensubtitles-scraper/pyppeteer/pyppeteer/__init__.py", line 52, in launch
    return await self._launcher.launch(**kwargs)
  File "/home/user/src/opensubtitles-scraper/pyppeteer/pyppeteer/launcher.py", line 321, in launch
    raise original_exception
  File "/home/user/src/opensubtitles-scraper/pyppeteer/pyppeteer/launcher.py", line 304, in launch
    connection = await runner.setupConnection(
  File "/home/user/src/opensubtitles-scraper/pyppeteer/pyppeteer/launcher.py", line 166, in setupConnection
    transport = await WebsocketTransport.create(uri=browser_ws_endpoint)
  File "/home/user/src/opensubtitles-scraper/pyppeteer/pyppeteer/websocket_transport.py", line 19, in create
    await connect(
  File "/nix/store/8pxfz6km4sgfpxra81y4k5q6cplqvxnn-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/nix/store/8pxfz6km4sgfpxra81y4k5q6cplqvxnn-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/nix/store/8pxfz6km4sgfpxra81y4k5q6cplqvxnn-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/client.py", line 303, in handshake
    key = build_request(request_headers)
  File "/nix/store/8pxfz6km4sgfpxra81y4k5q6cplqvxnn-python3-3.10.12-env/lib/python3.10/site-packages/websockets/legacy/handshake.py", line 30, in build_request
    key = generate_key()
  File "/nix/store/8pxfz6km4sgfpxra81y4k5q6cplqvxnn-python3-3.10.12-env/lib/python3.10/site-packages/websockets/utils.py", line 20, in generate_key
    key = secrets.token_bytes(16)
AttributeError: module 'secrets' has no attribute 'token_bytes'
```

</details>

</details>
